export const labels = {
  en: {
    customers: "Customers",
    revenue: "Revenue",
    products: "Products",
    sales: "Sales",
    salesRevenue: "Sales Revenue",
    selectALanguage: "Select A Language",
  },
  ja: {
    customers: "お客様",
    revenue: "収入",
    products: "商品",
    sales: "売上",
    salesRevenue: "売上高",
    selectALanguage: "選択言語",
  },
  ko: {
    customers: "고객",
    revenue: "수입",
    products: "제품",
    sales: "매출",
    salesRevenue: "매출 수익",
    selectALanguage: "언어 선택",
  },
  de: {
    customers: "Kunde",
    revenue: "Einnahmen",
    products: "Produkte",
    sales: "Umsatz",
    salesRevenue: "Umsatzerlöse",
    selectALanguage: "Sprache auswählen",
  },
  fr: {
    customers: "Client",
    revenue: "Revenu",
    products: "Produits",
    sales: "Chiffre d'affaires",
    salesRevenue: "Chiffre d'affaires",
    selectALanguage: "Sélectionner une langue",
  },
  ru: {
    customers: "Клиент",
    revenue: "Доход",
    products: "Продукты",
    sales: "Продажи",
    salesRevenue: "Выручка",
    selectALanguage: "Выберите язык",
  },
};
